export const signUp="http://localhost:5000/user"
export const signIn="http://localhost:5000/login"
export const addBlog="http://localhost:5000/addblog"
export const allBlog="http://localhost:5000/allblog"
export const oneBlog="http://localhost:5000/blogs/"
export const deleteBlog="http://localhost:5000/deleteblog/"